on:
  push:
    tags:
      - v*.*.*

name: Publishing Kelk to crates.io

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1

      - name: docs check
        run: cargo doc --no-deps

      - name: installing tomli
        run: pip3 install tomli

      - name: check the crates
        run: python3 .github/workflows/publish.py check -v

      - name: publish the crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: python3 .github/workflows/publish.py publish --dry-run -v
